const moduleStatusItems = [
  {
    id: "workspace_home",
    label: "Home",
    badge: "active",
    contract: "shell-owned workspace entry",
    runtime: "static home panel inside the workspace shell",
    authority: "navigation/context only; no product, proof, selector, or compliance authority",
    uiEvidence: "home panel and module maturity registry",
    nextStep: "homepage/progress map alignment before the next read-only integration slice",
  },
  {
    id: "novon_website",
    label: "Novon website",
    badge: "read-only",
    contract: "shell-owned special view",
    runtime: "mounted as a shell special view",
    authority: "read-only website reference only; no product/proof/selector authority",
    uiEvidence: "sidebar link and shell-owned website view",
    nextStep: "keep separate from runtime product authority",
  },
  {
    id: "hubspot_project_context",
    label: "HubSpot / Project Context",
    badge: "context",
    contract: "partial shell/project context integration",
    runtime: "visible/linkage exists where already implemented",
    authority: "project/customer context only; not product/proof/selector authority",
    uiEvidence: "shell/project/admin surfaces",
    nextStep: "keep separate from module status unless formalised as a module",
  },
  {
    id: "cs_selector",
    label: "Selector",
    badge: "readiness-preview",
    contract: "product-surface / readiness-preview accepted",
    runtime: "DB-backed candidate preview with selected-truth, workflow, payload-preview, selected-result dependency, and spec-build readiness preview visible",
    authority: "resolves selections only; no slug/spec/payload/RunTable/IES/proof/approval/record/custody/Board Data write authority",
    uiEvidence: "product-facing controls, selected-truth summary, workflow metadata, payload preview, selected-result dependency, and spec-build readiness preview",
    nextStep: "consume an accepted selected Engine/RunTable result only after the read-only/fail-closed source contract is integrated",
  },
  {
    id: "board_data",
    label: "Board Data",
    badge: "read-only",
    contract: "accepted read-only metadata source",
    runtime: "shell mounted + /api/board-data/status with redacted product/component metadata summaries",
    authority: "product/component metadata authority only; no downstream mutation, no proof authority, and downstream modules must not mutate Selector, Lab Proof, or Board Data",
    uiEvidence: "diagnostic status panel and redacted board detail inspector",
    nextStep: "keep Board Data read-only while downstream modules consume safe metadata through explicit contracts",
  },
  {
    id: "ecg_driver",
    label: "ECG Driver",
    badge: "planned",
    contract: "placeholder only; formal contract not accepted yet",
    runtime: "sidebar placeholder only; no mounted module route",
    authority: "none; does not mutate selector, board data, photometry, or proof state",
    uiEvidence: "planned sidebar icon only",
    nextStep: "write the ECG driver contract before mounting active behaviour",
  },
  {
    id: "ies_builder",
    label: "IES Builder",
    badge: "contract-ready",
    contract: "candidate-output contract-ready",
    runtime: "shell mounted + /api/ies-builder/status; candidate-output diagnostics only and blocked on an accepted selected Engine/RunTable result",
    authority: "candidate artefact boundary only; no proof authority, upload, parse, export, generation, polar preview, raw candela, raw IES, or raw Engine payload exposure",
    uiEvidence: "diagnostic status panel showing selected-engine-runtable-result-required as the main blocker",
    nextStep: "candidate-output handoff after an accepted selected Engine/RunTable result exists",
  },
  {
    id: "troffer_light",
    label: "Troffer",
    badge: "planned",
    contract: "placeholder only; formal contract not accepted yet",
    runtime: "sidebar placeholder only; no mounted module route",
    authority: "none; no product/proof/selector/compliance authority",
    uiEvidence: "planned sidebar icon only",
    nextStep: "write the troffer contract before mounting active behaviour",
  },
  {
    id: "lab_proof",
    label: "Lab Proof",
    badge: "authority-contract diagnostic",
    contract: "authority-contract diagnostic",
    runtime: "mounted shell inspector + /api/lab-proof/status; blocked until an approved Lab authority contract exists",
    authority: "candidate refs are not proof; no production proof claims, production proof authority, certification, approval, or downstream write authority",
    uiEvidence: "visible diagnostic inspector with safe metadata summaries and missing-authority-contract blocker copy",
    nextStep: "approve a Lab authority contract before any production proof claim can exist",
  },
  {
    id: "authority_reference_materialiser",
    label: "Authority Reference / Materialiser",
    badge: "admin-only",
    contract: "accepted",
    runtime: "materialiser foundation + Google reader + Admin/Dev status",
    authority: "server-side materialised-source refresh only; active promotion separate",
    uiEvidence: "Admin/Dev materialiser card",
    nextStep: "configured Google dry-run/live materialised refresh proof",
  },
  {
    id: "admin_dev",
    label: "Admin / Dev",
    badge: "active",
    contract: "accepted",
    runtime: "mounted protected admin module",
    authority: "developer/admin diagnostics and controlled tools",
    uiEvidence: "diagnostics, archive/sync/materialiser panels",
    nextStep: "keep stable; avoid becoming a dumping ground",
  },
  {
    id: "scene_builder",
    label: "Scene Builder",
    badge: "readiness-diagnostic",
    contract: "structural/readiness diagnostic",
    runtime: "mounted read-only diagnostic module; depends on future Selector + Engine/RunTable context contracts before active scene behaviour",
    authority: "no scene generation, bindings logic, schedule editor, DALI/DMX export, commissioning/proof/compliance authority, or downstream write authority",
    uiEvidence: "structural/readiness diagnostic panel",
    nextStep: "readiness metadata shell only until future Selector + Engine/RunTable context contracts are accepted",
  },
  {
    id: "emergence",
    label: "Emergency / EGRES",
    badge: "read-only diagnostic",
    contract: "Selector captures emergency/egress intent now; Engine/RunTable handles placement later; EGRES package diagnostics remain read-only",
    runtime: "mounted module as emergence; egres may route as an alias to the same diagnostic module only",
    authority: "no AS2293 certification, commissioning signoff, row/tag workflow, emergency compliance approval, project approval, authority approval, donor code, or server endpoint",
    uiEvidence: "Emergency / EGRES diagnostic panel plus Selector Egress & Accessories intent fields",
    nextStep: "EGRES package evidence readiness after selected-result and placement contracts mature",
  },
  {
    id: "compliance_matters",
    label: "Compliance Matters",
    badge: "evidence/risk diagnostic",
    contract: "read-only evidence/risk/review diagnostic; readiness matrix later",
    runtime: "mounted diagnostic shell module; blocked until EGRES/package evidence and authority chain exist",
    authority: "no certification, legal approval, code approval, NCC/BCA approval, AS/NZS approval, engineering signoff, project approval, or authority approval",
    uiEvidence: "read-only diagnostic panel at /workspace?module=compliance_matters",
    nextStep: "compliance readiness matrix only after EGRES/package evidence and authority chain are available",
  },
  {
    id: "coordinated_surfaces",
    label: "Coordinated Surfaces",
    badge: "diagnostic",
    contract: "read-only naming/context diagnostic for coordinated_surfaces / ceiling / ceiling_coord",
    runtime: "mounted diagnostic shell module at /workspace?module=coordinated_surfaces",
    authority: "diagnostic-only; no drawing, setout, clash, geometry, Selector, RunTable, payload, or coordination signoff authority",
    uiEvidence: "read-only diagnostic panel with route/id contract and mutation guardrails",
    nextStep: "future ceiling/surface considerations only after separate authority contract approval",
  },
  {
    id: "knowledge_base",
    label: "Knowledge Base",
    badge: "diagnostic",
    group: "Knowledge & Governance",
    contract: "read-only diagnostic Knowledge Base / Knowledge Cards reference shell",
    runtime: "mounted shell module at /workspace?module=knowledge_base; no KC editing, publishing, approval automation, HubSpot write, CLX mutation, or hidden write-back",
    authority: "references governed knowledge only; does not create authority or override code truth, Board Data, Lab Proof, Module Cards, or Controlled Records",
    uiEvidence: "read-only diagnostic panels for runtime status flags, KC authority boundaries, proposed knowledge card fields, relationship map, and future diagnostics",
    nextStep: "future governed knowledge updates only after explicit human approval and separate write-authority contracts",
  },
  {
    id: "knowledge_spine",
    label: "Knowledge Spine",
    badge: "diagnostic",
    group: "Knowledge & Governance",
    contract: "read-only diagnostic Knowledge Spine / Module Cards shell",
    runtime: "mounted shell module at /workspace?module=knowledge_spine; no active Liora, KC, CLX, ledger, HubSpot, or RepoMap writes",
    authority: "describes runtime/module authority boundaries only; does not override code truth, Board Data, Lab proof, Selector, IES Builder, Compliance, or EGRES",
    uiEvidence: "read-only diagnostic panels for runtime status, module card fields, KC/CLX/Ledger/Liora/RREG/Engine Flow relationships, and keep/shelve/retire decisions",
    nextStep: "rebuild KC, CLX, Ledger, Liora, RREG, Engine Flow, and RepoMap read-only first after separate contracts",
  },
  {
    id: "controlled_records",
    label: "Controlled Records / Ledger",
    badge: "provenance diagnostic",
    group: "Knowledge & Governance",
    contract: "provenance/disposition/audit-trail diagnostic",
    runtime: "mounted shell module at /workspace?module=controlled_records; no evidence ingestion, record mutation, ledger writer, HubSpot write, KC write, CLX write, Lab Ledger mutation, or Liora automation in this slice",
    authority: "does not prove, approve, certify, assign authority, transfer custody, create governed truth, or act as a task/auto-fix workflow",
    uiEvidence: "read-only diagnostic panels for runtime flags, controlled record lifecycle, provenance fields, disposition fields, audit-trail map, and Ledger Health checks",
    nextStep: "Controlled Records provenance wiring only after separate governed contracts approve evidence intake and record mutation",
  },
  {
    id: "canonical_language",
    label: "Canonical Language",
    badge: "diagnostic",
    group: "Knowledge & Governance",
    contract: "read-only diagnostic Canonical Language / CLX shell",
    runtime: "mounted shell module at /workspace?module=canonical_language; no CLX editing, glossary mutation, KC write-back, HubSpot write, Selector mutation, or hidden write-back",
    authority: "vocabulary control surface only; does not create authority or override Board Data, Lab Proof, code truth, Module Cards, or Controlled Records",
    uiEvidence: "read-only diagnostic panels for runtime flags, role boundaries, proposed canonical term fields, language relationships, and future diagnostics",
    nextStep: "future governed terminology changes only after explicit human approval and separate write-authority contracts",
  },
  {
    id: "liora_cockpit",
    label: "Liora Cockpit",
    badge: "diagnostic",
    group: "Knowledge & Governance",
    contract: "read-only diagnostic Liora Cockpit orchestration shell",
    runtime: "mounted shell module at /workspace?module=liora_cockpit; no message ingestion, chat agent, draft creation, sending, HubSpot call, KC/CLX write, Controlled Records write, RREG write, or runtime data mutation",
    authority: "orchestration cockpit only; does not silently approve, write, overwrite, merge, close, publish governed truth, replace human approval, or act as hidden central authority",
    uiEvidence: "read-only diagnostic panels for runtime flags, role boundaries, future intake lifecycle, provenance model, relationship map, disabled future actions, and forbidden actions",
    nextStep: "keep read-only until separate governed contracts approve capture/classify/route/draft/recommend behaviour",
  },
  {
    id: "rreg",
    label: "Roles & Responsibilities",
    badge: "mapping diagnostic",
    group: "Knowledge & Governance",
    contract: "responsibility/reviewer/approver/custody mapping only",
    runtime: "mounted shell module at /workspace?module=rreg; no donor RREG import, seed script, POST endpoint, people assignment UI, custody transfer action, approval button, permission enforcement, or hidden write-back",
    authority: "does not grant authority, approve, assign people, enforce permissions, transfer custody, mutate governed runtime data, or replace explicit human approval",
    uiEvidence: "read-only diagnostic panels for runtime flags, role boundaries, responsibility/reviewer/approver/custody concepts, proposed schema fields, relationships, and future diagnostics",
    nextStep: "reviewer/approver/custody mapping only after separate governed contracts; no write-back until explicitly approved",
  },
  {
    id: "engine_flow",
    label: "Engine Flow",
    badge: "diagnostic",
    group: "Knowledge & Governance",
    contract: "static process/confidence/proof-boundary diagnostic map only",
    runtime: "mounted shell module at /workspace?module=engine_flow; no engine execution, Selector firing, IES generation, RunTable generation, payload generation, drawing generation, or Lab proof claim",
    authority: "explains process, maps confidence, and maps proof boundaries only; does not resolve, execute, mutate, generate, approve, prove, or override Board Data or Lab Proof",
    uiEvidence: "read-only diagnostic panels for runtime flags, manual and runtime process maps, confidence labels, proof-boundary labels, allowed consumers, and disallowed claims",
    nextStep: "keep distinct from Engine / RunTable implementation status while execution and generation remain unapproved",
  },
  {
    id: "engine_runtable",
    label: "Engine / RunTable",
    badge: "domain-kernel",
    group: "Engineering Authority",
    contract: "domain-kernel / selected-result source-contract",
    runtime: "pure runtime kernel started; selected-result source contract is fail-closed with no route, no POST endpoint, no Engine execution, no RunTable generation, no selected-result ingestion/persistence, and no stale comparison yet",
    authority: "no payload, IES, drawing, proof, approval, certification, write, persistence, raw output exposure, or downstream mutation authority",
    uiEvidence: "selector gate covers Engine RunTable domain kernel and RunTable selected-result source contract diagnostics",
    nextStep: "selected-result source integration as read-only/fail-closed before IES Builder candidate-output handoff",
  },
];

export const MODULE_STATUS_REGISTRY = Object.freeze(moduleStatusItems.map((item) => Object.freeze({ ...item })));

const STATUS_BY_ID = new Map(MODULE_STATUS_REGISTRY.map((item) => [item.id, item]));

export function moduleStatusFor(statusId) {
  return STATUS_BY_ID.get(statusId) || null;
}

export function moduleStatusRows(status) {
  if (!status) return [];
  return [
    ["Contract", status.contract],
    ["Runtime", status.runtime],
    ["Authority", status.authority],
    ["UI evidence", status.uiEvidence],
    ["Next step", status.nextStep],
  ];
}

export function moduleStatusTooltip(status) {
  if (!status) return "";
  return [
    `${status.label} — ${status.badge}`,
    ...moduleStatusRows(status).map(([label, value]) => `${label}: ${value}`),
  ].join("\n");
}
