const moduleStatusItems = [
  {
    id: "workspace_home",
    label: "Home",
    badge: "active",
    contract: "shell-owned workspace entry",
    runtime: "static home panel inside the workspace shell",
    authority: "navigation/context only; no product, proof, selector, or compliance authority",
    uiEvidence: "home panel and module maturity registry",
    nextStep: "keep lightweight and non-boot-critical",
  },
  {
    id: "novon_website",
    label: "Novon website",
    badge: "read-only",
    contract: "shell-owned special view",
    runtime: "mounted as a shell special view",
    authority: "read-only website reference only; no product/proof/selector authority",
    uiEvidence: "sidebar link and shell-owned website view",
    nextStep: "keep separate from runtime product authority",
  },
  {
    id: "hubspot_project_context",
    label: "HubSpot / Project Context",
    badge: "context",
    contract: "partial shell/project context integration",
    runtime: "visible/linkage exists where already implemented",
    authority: "project/customer context only; not product/proof/selector authority",
    uiEvidence: "shell/project/admin surfaces",
    nextStep: "keep separate from module status unless formalised as a module",
  },
  {
    id: "cs_selector",
    label: "Selector",
    badge: "diagnostic",
    contract: "accepted",
    runtime: "mounted shell module with reference/status diagnostics",
    authority: "resolves selections; no Lab proof authority",
    uiEvidence: "diagnostic panels and field/state/default-preview scaffolds",
    nextStep: "manual constraint UI / controlled resolving progression",
  },
  {
    id: "board_data",
    label: "Board Data",
    badge: "read-only",
    contract: "accepted",
    runtime: "shell mounted + /api/board-data/status",
    authority: "read-only product/component metadata authority; does not mutate Selector",
    uiEvidence: "diagnostic status panel",
    nextStep: "safe table summaries / redacted board detail inspector",
  },
  {
    id: "ecg_driver",
    label: "ECG Driver",
    badge: "planned",
    contract: "placeholder only; formal contract not accepted yet",
    runtime: "sidebar placeholder only; no mounted module route",
    authority: "none; does not mutate selector, board data, photometry, or proof state",
    uiEvidence: "planned sidebar icon only",
    nextStep: "write the ECG driver contract before mounting active behaviour",
  },
  {
    id: "ies_builder",
    label: "IES Builder / Photometry",
    badge: "candidate-only",
    contract: "accepted",
    runtime: "shell mounted + /api/ies-builder/status",
    authority: "candidate photometry only; not proof authority",
    uiEvidence: "diagnostic status panel",
    nextStep: "fixture-only parser diagnostics, no upload/export yet",
  },
  {
    id: "troffer_light",
    label: "Troffer Light",
    badge: "planned",
    contract: "placeholder only; formal contract not accepted yet",
    runtime: "sidebar placeholder only; no mounted module route",
    authority: "none; no product/proof/selector/compliance authority",
    uiEvidence: "planned sidebar icon only",
    nextStep: "write the troffer contract before mounting active behaviour",
  },
  {
    id: "lab_proof",
    label: "Lab Proof",
    badge: "diagnostic",
    contract: "boundary accepted",
    runtime: "mounted shell inspector + /api/lab-proof/status",
    authority: "read-only diagnostic proof boundary; no production proof claims or production proof authority",
    uiEvidence: "visible diagnostic inspector with safe metadata summaries only",
    nextStep: "future Lab authority contract required before production proof can exist",
  },
  {
    id: "authority_reference_materialiser",
    label: "Authority Reference / Materialiser",
    badge: "admin-only",
    contract: "accepted",
    runtime: "materialiser foundation + Google reader + Admin/Dev status",
    authority: "server-side materialised-source refresh only; active promotion separate",
    uiEvidence: "Admin/Dev materialiser card",
    nextStep: "configured Google dry-run/live materialised refresh proof",
  },
  {
    id: "admin_dev",
    label: "Admin / Dev",
    badge: "active",
    contract: "accepted",
    runtime: "mounted protected admin module",
    authority: "developer/admin diagnostics and controlled tools",
    uiEvidence: "diagnostics, archive/sync/materialiser panels",
    nextStep: "keep stable; avoid becoming a dumping ground",
  },
  {
    id: "scene_builder",
    label: "Scene Builder",
    badge: "diagnostic",
    contract: "structural shell contract",
    runtime: "mounted module",
    authority: "contract/context consumer only",
    uiEvidence: "structural diagnostic panel",
    nextStep: "downstream module map before active scene behaviour",
  },
  {
    id: "emergence",
    label: "Emergency / EGRES",
    badge: "diagnostic",
    contract: "naming/route contract clarified; runtime id is emergence, downstream lane is egres, donor vocabulary is EGRES / Emergency",
    runtime: "mounted module as emergence; egres may route as an alias to the same diagnostic module only",
    authority: "diagnostic-only; no AS2293 certification, commissioning signoff, emergency compliance approval, project approval, authority approval, row/tag workflow, donor code, or server endpoint",
    uiEvidence: "Emergency / EGRES diagnostic panel shows route/lane/vocabulary contract and explicit non-authority wording",
    nextStep: "future EGRES workflow only after a separate contract slice",
  },
  {
    id: "compliance_matters",
    label: "Compliance Matters",
    badge: "diagnostic",
    contract: "read-only evidence/risk/contribution map",
    runtime: "mounted diagnostic shell module",
    authority: "no certification/legal/code approval, NCC/BCA approval, AS/NZS approval, engineering signoff, project approval, or authority approval",
    uiEvidence: "read-only diagnostic panel at /workspace?module=compliance_matters",
    nextStep: "wait for EGRES package evidence before compliance readiness can progress",
  },
  {
    id: "coordinated_surfaces",
    label: "Coordinated Surfaces / Ceiling",
    badge: "diagnostic",
    contract: "read-only naming/context diagnostic for coordinated_surfaces / ceiling / ceiling_coord",
    runtime: "mounted diagnostic shell module at /workspace?module=coordinated_surfaces",
    authority: "diagnostic-only; no drawing, setout, clash, geometry, Selector, RunTable, payload, or coordination signoff authority",
    uiEvidence: "read-only diagnostic panel with route/id contract and mutation guardrails",
    nextStep: "future ceiling/surface considerations only after separate authority contract approval",
  },
  {
    id: "knowledge_spine",
    label: "Knowledge Spine",
    badge: "diagnostic",
    group: "Knowledge / Governance",
    contract: "read-only diagnostic Knowledge Spine / Module Cards shell",
    runtime: "mounted shell module at /workspace?module=knowledge_spine; no active Liora, KC, CLX, ledger, HubSpot, or RepoMap writes",
    authority: "describes runtime/module authority boundaries only; does not override code truth, Board Data, Lab proof, Selector, IES Builder, Compliance, or EGRES",
    uiEvidence: "read-only diagnostic panels for runtime status, module card fields, KC/CLX/Ledger/Liora/RREG/Engine Flow relationships, and keep/shelve/retire decisions",
    nextStep: "rebuild KC, CLX, Ledger, Liora, RREG, Engine Flow, and RepoMap read-only first after separate contracts",
  },
  {
    id: "controlled_records",
    label: "Controlled Records / Ledger",
    badge: "diagnostic",
    group: "Knowledge / Governance",
    contract: "read-only diagnostic Controlled Records / Ledger Blueprint shell",
    runtime: "mounted shell module at /workspace?module=controlled_records; no active intake, record writer, ledger writer, HubSpot write, KC write, CLX write, Lab Ledger mutation, or Liora automation",
    authority: "evidence/disposition trail blueprint only; not a task list, auto-fix authority, approval workflow, governed truth writer, universal Lab Ledger, or derived action source of truth",
    uiEvidence: "read-only diagnostic panels for runtime flags, controlled record lifecycle, proposed record/schema fields, old-concept mapping, and Ledger Health diagnostic checks",
    nextStep: "future Intake Ledger and domain-specific controlled record implementations only after separate governed contracts",
  },
];

export const MODULE_STATUS_REGISTRY = Object.freeze(moduleStatusItems.map((item) => Object.freeze({ ...item })));

const STATUS_BY_ID = new Map(MODULE_STATUS_REGISTRY.map((item) => [item.id, item]));

export function moduleStatusFor(statusId) {
  return STATUS_BY_ID.get(statusId) || null;
}

export function moduleStatusRows(status) {
  if (!status) return [];
  return [
    ["Contract", status.contract],
    ["Runtime", status.runtime],
    ["Authority", status.authority],
    ["UI evidence", status.uiEvidence],
    ["Next step", status.nextStep],
  ];
}

export function moduleStatusTooltip(status) {
  if (!status) return "";
  return [
    `${status.label} — ${status.badge}`,
    ...moduleStatusRows(status).map(([label, value]) => `${label}: ${value}`),
  ].join("\n");
}
