const DEFAULT_ADMIN_TOOLS = [
  {
    toolId: "diagnostics.shell",
    label: "Shell Diagnostics",
    category: "diagnostics",
    owner: "shell",
    placement: "developer-affordance",
    requiredRole: "developer",
    requiredPrivilege: "diagnostics:view",
    bootCritical: false,
    readWriteMode: "read-only",
    routeMode: "plugin-panel",
    auditRequired: "none",
    confirmationRequired: false,
    failureMode: "visible-warning",
    nonBootCriticalFallback: "hide-tool-and-continue-shell-boot",
    providerBoundary: "none",
    secretBoundary: "no-secrets-browser-visible",
    projectScoped: false,
    tenantScoped: false,
    moduleScoped: false,
    statusSource: "services.diagnostics.getSnapshot",
    healthSource: "/health",
  },
  {
    toolId: "runtime.config-status",
    label: "Runtime Config Status",
    category: "provider-config",
    owner: "shell",
    placement: "developer-affordance",
    requiredRole: "developer",
    requiredPrivilege: "runtime-config:view",
    bootCritical: false,
    readWriteMode: "read-only",
    routeMode: "plugin-panel",
    auditRequired: "none",
    confirmationRequired: false,
    failureMode: "visible-warning",
    nonBootCriticalFallback: "hide-tool-and-continue-shell-boot",
    providerBoundary: "runtime-config",
    secretBoundary: "secret-presence-only",
    projectScoped: false,
    tenantScoped: true,
    moduleScoped: false,
    statusSource: "/api/runtime-config/status",
    healthSource: "/health",
  },
  {
    toolId: "authority-reference.status",
    label: "Authority Reference Status",
    category: "authority-reference",
    owner: "shell",
    placement: "protected-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "authority-reference:view",
    bootCritical: false,
    readWriteMode: "read-only",
    routeMode: "plugin-panel",
    auditRequired: "read-summary",
    confirmationRequired: false,
    failureMode: "visible-warning",
    nonBootCriticalFallback: "authority-fallback-and-continue-shell-boot",
    providerBoundary: "authority-reference",
    secretBoundary: "secret-presence-only",
    projectScoped: false,
    tenantScoped: true,
    moduleScoped: false,
    statusSource: "/api/authority-reference/status",
    healthSource: "/health",
  },
  {
    toolId: "authority-reference.sync",
    label: "Authority Reference Sync",
    category: "authority-reference",
    owner: "shell",
    placement: "protected-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "authority-reference:sync",
    bootCritical: false,
    readWriteMode: "explicit-write",
    routeMode: "plugin-panel",
    auditRequired: "admin-proof",
    confirmationRequired: true,
    failureMode: "admin-review-required",
    nonBootCriticalFallback: "disable-sync-action-and-continue-shell-boot",
    providerBoundary: "authority-reference",
    secretBoundary: "server-env-only",
    projectScoped: false,
    tenantScoped: true,
    moduleScoped: false,
    statusSource: "/api/authority-reference/status",
    healthSource: "/api/authority-reference/sync?dryRun=true",
  },
  {
    toolId: "hubspot.auth-status",
    label: "HubSpot Auth Status",
    category: "hubspot",
    owner: "shell",
    placement: "protected-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "hubspot:view",
    bootCritical: false,
    readWriteMode: "read-only",
    routeMode: "plugin-panel",
    auditRequired: "read-summary",
    confirmationRequired: false,
    failureMode: "visible-warning",
    nonBootCriticalFallback: "crm-enrichment-unavailable-and-continue-shell-boot",
    providerBoundary: "hubspot",
    secretBoundary: "secret-presence-only",
    projectScoped: false,
    tenantScoped: true,
    moduleScoped: false,
    statusSource: "/api/hubspot/auth-status",
    healthSource: "/health",
  },
  {
    toolId: "hubspot.read-status",
    label: "HubSpot Read Status",
    category: "hubspot",
    owner: "shell",
    placement: "protected-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "hubspot:view",
    bootCritical: false,
    readWriteMode: "read-only",
    routeMode: "plugin-panel",
    auditRequired: "read-summary",
    confirmationRequired: false,
    failureMode: "visible-warning",
    nonBootCriticalFallback: "crm-enrichment-unavailable-and-continue-shell-boot",
    providerBoundary: "hubspot",
    secretBoundary: "secret-presence-only",
    projectScoped: true,
    tenantScoped: true,
    moduleScoped: false,
    statusSource: "/api/hubspot/read",
    healthSource: "/api/hubspot/auth-status",
  },
  {
    toolId: "hubspot.deal-writeback-preflight",
    label: "HubSpot Deal Writeback Preflight",
    category: "hubspot",
    owner: "shell",
    placement: "protected-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "hubspot:writeback-preflight",
    bootCritical: false,
    readWriteMode: "preflight-only",
    routeMode: "plugin-panel",
    auditRequired: "read-summary",
    confirmationRequired: false,
    failureMode: "visible-warning",
    nonBootCriticalFallback: "disable-writeback-preflight-and-continue-shell-boot",
    providerBoundary: "hubspot",
    secretBoundary: "secret-presence-only",
    projectScoped: true,
    tenantScoped: true,
    moduleScoped: false,
    statusSource: "/api/hubspot/deal-writeback/preflight",
    healthSource: "/health",
  },
  {
    toolId: "hubspot.repair-relink",
    label: "HubSpot Repair / Relink",
    category: "repair",
    owner: "shell",
    placement: "protected-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "hubspot:repair",
    bootCritical: false,
    readWriteMode: "repair-write",
    routeMode: "plugin-panel",
    auditRequired: "admin-proof",
    confirmationRequired: true,
    failureMode: "admin-review-required",
    nonBootCriticalFallback: "hide-tool-and-continue-shell-boot",
    providerBoundary: "hubspot",
    secretBoundary: "server-env-only",
    projectScoped: true,
    tenantScoped: true,
    moduleScoped: false,
    statusSource: "deferred",
    healthSource: "deferred",
  },
  {
    toolId: "timeline.policy-inspector",
    label: "Timeline Policy Inspector",
    category: "diagnostics",
    owner: "shell",
    placement: "developer-affordance",
    requiredRole: "developer",
    requiredPrivilege: "timeline-policy:view",
    bootCritical: false,
    readWriteMode: "read-only",
    routeMode: "plugin-panel",
    auditRequired: "none",
    confirmationRequired: false,
    failureMode: "visible-warning",
    nonBootCriticalFallback: "hide-tool-and-continue-shell-boot",
    providerBoundary: "none",
    secretBoundary: "no-secrets-browser-visible",
    projectScoped: true,
    tenantScoped: false,
    moduleScoped: false,
    statusSource: "services.timelinePolicy.getTimelinePolicySnapshot",
    healthSource: "services.diagnostics.getSnapshot",
  },
  {
    toolId: "review-history.admin",
    label: "Review / History Admin",
    category: "review-history",
    owner: "shell",
    placement: "protected-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "review-history:admin",
    bootCritical: false,
    readWriteMode: "read-only",
    routeMode: "plugin-panel",
    auditRequired: "read-summary",
    confirmationRequired: false,
    failureMode: "visible-warning",
    nonBootCriticalFallback: "hide-tool-and-continue-shell-boot",
    providerBoundary: "none",
    secretBoundary: "no-secrets-browser-visible",
    projectScoped: true,
    tenantScoped: false,
    moduleScoped: false,
    statusSource: "deferred",
    healthSource: "deferred",
  },
  {
    toolId: "tenant.occurrence-setup",
    label: "Tenant / Occurrence Setup",
    category: "tenant-setup",
    owner: "shell",
    placement: "separate-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "tenant-setup:admin",
    bootCritical: false,
    readWriteMode: "explicit-write",
    routeMode: "separate-admin-surface",
    auditRequired: "admin-proof",
    confirmationRequired: true,
    failureMode: "admin-review-required",
    nonBootCriticalFallback: "hide-tool-and-continue-shell-boot",
    providerBoundary: "tenant-provider",
    secretBoundary: "server-env-only",
    projectScoped: false,
    tenantScoped: true,
    moduleScoped: false,
    statusSource: "deferred",
    healthSource: "deferred",
  },
  {
    toolId: "provider.mapping-inspector",
    label: "Provider Mapping Inspector",
    category: "provider-config",
    owner: "shell",
    placement: "protected-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "provider-mapping:view",
    bootCritical: false,
    readWriteMode: "read-only",
    routeMode: "plugin-panel",
    auditRequired: "read-summary",
    confirmationRequired: false,
    failureMode: "visible-warning",
    nonBootCriticalFallback: "hide-tool-and-continue-shell-boot",
    providerBoundary: "tenant-provider",
    secretBoundary: "secret-presence-only",
    projectScoped: false,
    tenantScoped: true,
    moduleScoped: false,
    statusSource: "deferred",
    healthSource: "deferred",
  },
  {
    toolId: "cleanup.repair",
    label: "Cleanup / Repair",
    category: "repair",
    owner: "shell",
    placement: "protected-admin-surface",
    requiredRole: "developer",
    requiredPrivilege: "cleanup:repair",
    bootCritical: false,
    readWriteMode: "repair-write",
    routeMode: "plugin-panel",
    auditRequired: "admin-proof",
    confirmationRequired: true,
    failureMode: "admin-review-required",
    nonBootCriticalFallback: "hide-tool-and-continue-shell-boot",
    providerBoundary: "none",
    secretBoundary: "no-secrets-browser-visible",
    projectScoped: true,
    tenantScoped: false,
    moduleScoped: false,
    statusSource: "deferred",
    healthSource: "deferred",
  },
];

const REQUIRED_TOOL_FIELDS = [
  "toolId",
  "label",
  "category",
  "owner",
  "placement",
  "requiredRole",
  "requiredPrivilege",
  "bootCritical",
  "readWriteMode",
  "routeMode",
  "auditRequired",
  "confirmationRequired",
  "failureMode",
  "nonBootCriticalFallback",
  "providerBoundary",
  "secretBoundary",
  "projectScoped",
  "tenantScoped",
  "moduleScoped",
  "statusSource",
  "healthSource",
];

function cloneTool(tool) {
  return { ...tool };
}

function validateTool(tool) {
  const missing = REQUIRED_TOOL_FIELDS.filter((field) => !(field in tool));
  return {
    ok: missing.length === 0,
    missing,
    bootCritical: tool.bootCritical === true,
    owner: tool.owner || "unknown",
    browserSecretSafe: tool.secretBoundary !== "browser-visible-secret",
  };
}

export function createAdminToolRegistry({ tools = DEFAULT_ADMIN_TOOLS } = {}) {
  const registry = new Map();

  function register(tool) {
    const validation = validateTool(tool || {});
    const toolId = String(tool?.toolId || "").trim();
    if (!toolId) {
      throw new Error("Admin/tool registry entries require a stable toolId.");
    }
    registry.set(toolId, {
      ...tool,
      toolId,
      owner: tool.owner || "shell",
      bootCritical: tool.bootCritical === true,
      moduleScoped: tool.moduleScoped === true,
      browserSecretsExposed: false,
      validation,
    });
    return registry.get(toolId);
  }

  for (const tool of tools) {
    register(tool);
  }

  return {
    owner: "shell",
    status: "admin-tool-registry-foundation",
    register,
    get(toolId) {
      const tool = registry.get(toolId);
      return tool ? cloneTool(tool) : null;
    },
    list() {
      return [...registry.values()].map(cloneTool);
    },
    getStatusSnapshot() {
      const tools = this.list();
      const invalidTools = tools.filter((tool) => tool.validation?.ok !== true).map((tool) => ({
        toolId: tool.toolId,
        missing: tool.validation?.missing || [],
      }));
      const bootCriticalTools = tools.filter((tool) => tool.bootCritical === true).map((tool) => tool.toolId);
      const moduleScopedTools = tools.filter((tool) => tool.moduleScoped === true).map((tool) => tool.toolId);
      const browserSecretUnsafeTools = tools.filter((tool) => tool.secretBoundary === "browser-visible-secret").map((tool) => tool.toolId);
      return {
        owner: "shell",
        status: "ready",
        source: "admin-tool-registry-foundation",
        toolCount: tools.length,
        optionalToolsBootCriticalByDefault: false,
        browserSecretsExposed: false,
        nonSecretOnly: true,
        modulesRemainConsumersOnly: true,
        shellOwnsSharedAdminTooling: true,
        invalidTools,
        bootCriticalTools,
        moduleScopedTools,
        browserSecretUnsafeTools,
        tools,
      };
    },
  };
}
